### PR TITLE
Package and framework updates

### PR DESCRIPTION
**Pull request by waynemunro**
Undated nuget packages and .NET framework target. Also Fixed UseHttpSys issue

### CODE REVIEW

**Comment by MedAnd** [comment]
Hi @waynemunro, thanks for the PR! I'm starting to take a look and have an initial question:

- In IDataProtectionService.cs you are removing [assembly: FabricTransportServiceRemotingProvider(RemotingListener = RemotingListener.V2Listener, RemotingClient = RemotingClient.V2Client)], wondering the reason?

**Comment by waynemunro** [comment]
> Hi @waynemunro, thanks for the PR! I'm starting to take a look and have an initial question:
> 
> * In IDataProtectionService.cs you are removing [assembly: FabricTransportServiceRemotingProvider(RemotingListener = RemotingListener.V2Listener, RemotingClient = RemotingClient.V2Client)], wondering the reason?

This was causing the build to break so I removed it and it still works.

**Comment by MedAnd** [comment]
Which remoting client version are you using (V1 or v2)... just want to make sure both client versions are still working if we remove this attribute.

**Comment by waynemunro** [comment]
> Which remoting client version are you using (V1 or v2)... just want to make sure both client versions are still working if we remove this attribute.

Its using v2 assembly attribute again. I've pushed another commit

**Comment by MedAnd** [comment]
Merged & thanks for the PR! Will try to release updated nuget packages sometime this week.

**Comment by MedAnd** [comment]
@wynemunro - just published [version 1.0.5](https://www.nuget.org/packages/AspNetCore.DataProtection.ServiceFabric/1.0.5) on nuget... let me know if you find any issues ☺️

**Pull request merged**
