### PR TITLE
use .NET Core 2.0, upgrade SF nuget to 3.1.274

### PR DESCRIPTION
**Pull request by heavenwing**
use new asp.net core stateless web
can use alternative service uri
fix DataProtectionBuilderExtensions

### CODE REVIEW

**Comment by MedAnd** [comment]
Hi @heavenwing, having a look at this PR and some questions:

Did you mean to push the TestWeb project and all related files, seems like this is beyond the scope of the AspNetCore.DataProtection.ServiceFabric project?

Apart from upgrading to .NET Core 2.0 and SDK 3.1.274, I would like to better understand the intent of the PR. I see a comment "can use alternative service uri"... could you clarify why this is required, why the current approach does not work for you, what was not supported etc? 

Thx.

**Comment by heavenwing** [comment]
Hi @MedAnd

My TestWeb project is included in this solution, see here: https://github.com/heavenwing/AspNetCore.DataProtection.ServiceFabric/tree/master/TestWeb

My comment explain the reason of "can use alternative service uri" : https://github.com/MedAnd/AspNetCore.DataProtection.ServiceFabric/issues/4#issuecomment-392256385

And I push a new commit "fix PersistKeysToServiceFabric and use Task.Run to invoke async functions", it reference https://github.com/aspnet/DataProtection/blob/release%2F2.0/src/Microsoft.AspNetCore.DataProtection.AzureStorage

PS: because I change AspNetCore.DataProtection.ServiceFabric project to .NET Core 2.0, generated nuget packages of this project via SFNuget is larger than previous (around 32MB).  I can change it back to .NET 4.6.1, size is 8 MB. Which option is better?

**Comment by rfcdejong** [comment]
@heavenwing did you publish your package to SFNuGet? as I'm running into the same issue as you (the package is running on a different serviceUri) and this pull request is not closed I want to try out your solution without cloning the package manually.

**Comment by heavenwing** [comment]
@rfcdejong I don't publish NuGet package, just generated it in local.
In my real project, I copied source code into my SF App solution, and use my approach of this PR to use DataProtectionService.

**Comment by rfcdejong** [comment]
Skipped it cause we desided to use AzureStorage as we need it for other stuff as well, which works nicely as well. Currently encrypting it with a certificate from the cluster, but will use AzureKeyVault which is currently in 2.1.0 rc1 final soon.

**Comment by heavenwing** [comment]
@rfcdejong If your SF cluster is in Azure, using AzureStorage or AzureKeyVault is good choice.

**Comment by MedAnd** [comment]
Hi @heavenwing, thank you for the PR and feedback! I've finally found time to go through the issue and would like to split the PR into two releases. 

For the 1st release I would like to propose the following changes, upgrade and nuget: [PersistKeysToServiceFabric ServiceUri SDK Upgrade](https://github.com/MedAnd/AspNetCore.DataProtection.ServiceFabric/pull/6)

I believe this would allow support for older AspNetCore applications. 

For the 2nd release I would like to propose netstandard2.0 as TargetFramework with further Microsoft.AspNetCore Upgrade(s) to latest, with small refactor to use newer Microsoft.AspNetCore.DataProtection logic.

Let me know if this works for you and if I've missed anything...

**Comment by heavenwing** [comment]
That’s great.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MedAnd** [comment]
Hi @heavenwing, the first PR has been released on nuget: 

[AspNetCore.DataProtection.ServiceFabric 1.0.4](https://www.nuget.org/packages/AspNetCore.DataProtection.ServiceFabric/1.0.4)
[AspNetCore.DataProtection.ServiceFabric.Common 1.0.4](https://www.nuget.org/packages/AspNetCore.DataProtection.ServiceFabric/1.0.4)

PS. Wondering if this works for your project?

**Pull request closed without merging**
